name: Daily Auto Commit

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Make changes and commit (21f1003364@ds.study.iitm.ac.in)
        run: |
          echo "Automated update: $(date)" >> daily_update.log
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add daily_update.log
          git commit -m "Automated daily commit - $(date)"
          git push

